### PR TITLE
Mobilsdk 2795

### PR DESCRIPTION
**Pull request by awangvan**

### CODE REVIEW

**Comment by wayneburkett** [comment]
@awangvan I have one suggestion: could we pull the JavaScript files into their own `js` folder inside each example? I think that might make it just a little bit easier to follow the structure of the project, since there are a bunch of config and dot files in the parent dirs.

**Comment by awangvan** [comment]
> @awangvan I have one suggestion: could we pull the JavaScript files into their own `js` folder inside each example? I think that might make it just a little bit easier to follow the structure of the project, since there are a bunch of config and dot files in the parent dirs.

Sure. Does it include the App.js file as well?

**Comment by awangvan** [comment]
> @awangvan I have one suggestion: could we pull the JavaScript files into their own `js` folder inside each example? I think that might make it just a little bit easier to follow the structure of the project, since there are a bunch of config and dot files in the parent dirs.

Also I was trying to find a way to put a `shared` folder outside of the sample folders, and let each sample to import common js files from it, but it seems RN doesn't allow it. Is this the case?

**Comment by wayneburkett** [comment]
> Also I was trying to find a way to put a shared folder outside of the sample folders, and let each sample to import common js files from it, but it seems RN doesn't allow it. Is this the case?

@awangvan Oh, that's a really good idea. I would *think* it's possible, but I couldn't say for sure. Although, as far as I know, it should follow the normal JS `require` format. I don't think it should matter where the files are.

**Pull request merged**
